# Generated by Django 5.2.7 on 2025-10-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image_url',
            field=models.URLField(),
        ),
    ]
