# Generated by Django 5.2.7 on 2025-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0002_alter_dish_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
