# Generated by Django 5.2.7 on 2025-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_menu', '0003_alter_dish_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=200)),
                ('created_add', models.DateTimeField(auto_now=True)),
                ('adres', models.CharField(max_length=100)),
            ],
        ),
    ]
